name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea for a new feature or improvement? We'd love to hear it.

  - type: textarea
    id: problem
    attributes:
      label: Problem or motivation
      description: What problem does this solve, or what workflow would it improve?
      placeholder: "I find it difficult to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe what you'd like to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you've thought about or workarounds you're using.

  - type: dropdown
    id: mcp-client
    attributes:
      label: MCP Client
      description: Which client is this most relevant to? (optional)
      options:
        - All / not specific
        - Claude Code
        - Claude Desktop
        - Cursor
        - VS Code (Copilot)
        - Other

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Anything else (screenshots, links, examples, etc.).
